### ISSUE TITLE
Timezone issue when run dotnet on linux

### ISSUE THREAD

**Issue by urmiaking** [hamed-shirbandi/PersianDateTime.Core#1]
Hi. Time zone Ids are different in windows and linux. Please edit time zone in `PersianDateTime.cs` to :
`
public static TimeZoneInfo PersianTimeZoneInfo = RuntimeInformation.IsOSPlatform(OSPlatform.Windows) ? TimeZoneInfo.FindSystemTimeZoneById("Iran Standard Time") : TimeZoneInfo.FindSystemTimeZoneById("Asia/Tehran");
` in order to work on both linux and windows

**Comment by hamed-shirbandi** [comment]
Hi.
Linux Time Zone support added.
New package version published on the nuget.
thanks.
