### ISSUE TITLE
ساعت یک ساعت جلو نشان میدهد

### ISSUE THREAD

**Issue by aliakbarpoor** [hamed-shirbandi/PersianDateTime.Core#4]
با عدم تغییر ساعت رسمی ایران در بهار تایم برگشتی از PersianDateTime.Now یک ساعت جلو می باشد.

**Comment by hamed-shirbandi** [comment]
مشکل حل شد.
نسخه ی 2.0.2 روی nuget منتشر شد
ممنون از اطلاع رسانی
